on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

name: Build Linux x64 Roc CLI

jobs:
  build-roc-cli:
    name: Build the `roc` CLI
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v3

    - name: get commit SHA
      run:  echo "SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

    - name: get date
      run: echo "DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

    - name: build file name
      env:
        DATE: ${{ env.DATE }}
        SHA: ${{ env.SHA }}
      run: echo "RELEASE_FOLDER_NAME=roc_npm_nightly-linux_x64-$DATE-$SHA" >> $GITHUB_ENV

    - name: write version to file
      run: printf 'roc-npm nightly pre-release, built from commit ' > version.txt && git log --pretty=format:'%h' -n 1 >> version.txt && printf ' on ' >> version.txt && date -u >> version.txt

    - name: Build Docker image
      run: docker build -t docker-build-env ./.github/workflows/

    - name: Run build in Docker container
      run: |
        docker run --mount type=bind,source="$(pwd)",target=/app docker-build-env bash -c "\
        cd /app && \
        git clone --depth 1 https://github.com/roc-lang/roc.git && \
        cd roc && \
        cargo build --locked --profile=release-with-lto --bin roc && \
        ./target/release-with-lto/roc version"

    # this makes the roc binary a lot smaller
    # it currently errors on GitHub Actions with:
    #     strip: ./roc/target/release-with-lto/roc: could not create temporary file to hold stripped copy: cause of error unknown
    # - name: strip debug info
    #   run: strip ./roc/target/release-with-lto/roc
    - name: package release
      run: tar -czvf "${{ env.RELEASE_FOLDER_NAME }}.tar.gz" ./roc/target/release-with-lto/roc
    - name: print short commit SHA
      run: git rev-parse --short "$GITHUB_SHA"
    - name: print date
      run: date
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
         name: ${{ env.RELEASE_FOLDER_NAME }}.tar.gz
         path: ${{ env.RELEASE_FOLDER_NAME }}.tar.gz
         retention-days: 4
