name: Publish from Roc nightlies
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Set env variables
        run: |
          echo "DATE_STR=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo 'VERSION="0.0.1-${{ env.DATE_STR }}-nightly"' >> $GITHUB_ENV

      # download and unzip all the nightlies
      - name: Publish linux_x64 subpackage
        run: |
          cd subpackages/linux_x64/
          wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz
          tar xzf *.tar.gz
          rm *.tar.gz
          mv roc_nightly*/roc .
          sed -i "s/{{version}}/${VERSION}/g" package.json
          wc -c roc
          cat package.json
          npm publish

      # - name: Publish linux_arm64 subpackage
      #   run: |
      #     cd subpackages/linux_arm64/
      #     wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_arm64-latest.tar.gz
      #     tar xzf *.tar.gz
      #     rm *.tar.gz
      #     mv roc_nightly*/roc .
      #     sed -i "s/{{version}}/${VERSION}/g" package.json
      #     wc -c roc
      #     cat package.json
      #     npm publish

      - name: Publish darwin_arm64 subpackage
        run: |
          cd subpackages/darwin_arm64/
          wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_apple_silicon-latest.tar.gz
          tar xzf *.tar.gz
          rm *.tar.gz
          mv roc_nightly*/roc .
          sed -i "s/{{version}}/${VERSION}/g" package.json
          wc -c roc
          cat package.json
          npm publish

      - name: Publish darwin_x64 subpackage
        run: |
          cd subpackages/darwin_x64/
          wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-macos_x86_64-latest.tar.gz
          tar xzf *.tar.gz
          rm *.tar.gz
          mv roc_nightly*/roc .
          sed -i "s/{{version}}/${VERSION}/g" package.json
          wc -c roc
          cat package.json
          npm publish

      # Now that all the subpackages have been published, publish this one.
      - name: Publish roc-npm
        run: |
          sed -i "s/{{version}}/${VERSION}/g" package.json
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DATE_STR: $(date +%Y-%m-%d)
          VERSION: "0.0.1-${DATE_STR}-nightly"
